<?php
/**
 * @package		awf
 * @copyright	2014 Nicholas K. Dionysopoulos / Akeeba Ltd 
 * @license		GNU GPL version 3 or later
 */

namespace Awf\Platform\Joomla\Mvc\BackendDataView;

use Awf\Text\Text;

class Html extends Raw
{
	/**
	 * Executes before rendering the page for the Add task.
	 *
	 * @return  boolean  Return true to allow rendering of the page
	 */
	protected function onBeforeAdd()
	{
		// Hide main menu
		\JFactory::getApplication()->input->set('hidemainmenu', true);

		// Buttons
		\JToolBarHelper::apply();
		\JToolBarHelper::save();
		\JToolBarHelper::custom('savenew', 'save-new.png', 'save-new_f2.png', 'JTOOLBAR_SAVE_AND_NEW', false);
		\JToolBarHelper::cancel();

		return true;
	}

	/**
	 * Executes before rendering the page for the Edit task.
	 *
	 * @return  boolean  Return true to allow rendering of the page
	 */
	protected function onBeforeEdit()
	{
		// Hide main menu
		\JFactory::getApplication()->input->set('hidemainmenu', true);

		// Buttons
		\JToolBarHelper::apply();
		\JToolBarHelper::save();
		\JToolBarHelper::custom('savenew', 'save-new.png', 'save-new_f2.png', 'JTOOLBAR_SAVE_AND_NEW', false);
		\JToolBarHelper::cancel();

		return true;
	}

	/**
	 * Executes before rendering the page for the Read task.
	 *
	 * @return  boolean  Return true to allow rendering of the page
	 */
	protected function onBeforeRead()
	{
		// Buttons
		\JToolBarHelper::back();

		return true;
	}

	public function onBeforeBrowse()
	{
		// Buttons
		\JToolBarHelper::addNew();
		\JToolBarHelper::editList();

		\JToolBarHelper::divider();
		\JToolBarHelper::publishList();
		\JToolBarHelper::unpublishList();

		\JToolBarHelper::divider();
		$msg = Text::_($this->componentName . '_CONFIRM_DELETE');
		\JToolBarHelper::deleteList(strtoupper($msg));

		return parent::onBeforeBrowse(); // TODO: Change the autogenerated stub
	}
}